name: Python Lint Checker
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
      run: "pip install -r requirements.txt ; pylint **/*.py"