name: Python Lint Checker
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Backup current registrations
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
        chmod 0600 /tmp/ssh-key
        ssh -i /tmp/ssh-key -o StrictHostKeyChecking=no root@server.talk-about-it.ca \
        "mkdir -p /root/bc9_outputs/; \
        mkdir -p /root/agm_outputs/; \
        cp /var/cadets/bc9_online/bc9_outputs/*.json /root/bc9_outputs/ || echo 'No BC9 outputs found' ; \
        cp /var/cadets/agm/agm_outputs/*.json /root/agm_outputs/ || echo 'No AGM outputs exist' ; \
        cp /var/cadets/agm/registrations.csv /root/ || echo 'No AGM registration table exists' ;"
    - name: Publish BC9
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
        chmod 0600 /tmp/ssh-key
        ssh -i /tmp/ssh-key -o StrictHostKeyChecking=no root@server.talk-about-it.ca "cd /var; \
        rm -rf /var/cadets; \
        git clone --depth 1 https://github.com/lukebarone/cadets; \
        python3 -m pip install -r /var/cadets/bc9_online/requirements.txt; \
        chown -R www-data:www-data /var/cadets/bc9_online/bc9_outputs; \
        touch /var/cadets/bc9_online/get_bc9.log; \
        chown www-data:www-data /var/cadets/bc9_online/get_bc9.log"
    - name: Publish AGM
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
        chmod 0600 /tmp/ssh-key
        ssh -i /tmp/ssh-key -o StrictHostKeyChecking=no root@server.talk-about-it.ca \
        "python3 -m pip install -r /var/cadets/agm/requirements.txt; \
        mkdir -p /var/cadets/agm/agm_outputs; \
        chown -R www-data:www-data /var/cadets/agm/agm_outputs/; \
        touch /var/cadets/agm/agm.log; \
        chown www-data:www-data /var/cadets/agm/agm.log; \
        cp -f /var/cadets/uwsgi/vassals/agm.ini /etc/uwsgi/vassals/"
    - name: Restore registrations
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
        chmod 0600 /tmp/ssh-key
        ssh -i /tmp/ssh-key -o StrictHostKeyChecking=no root@server.talk-about-it.ca \
        "mkdir -p /var/cadets/bc9_online/bc9_outputs/; \
        mkdir -p /var/cadets/agm/agm_outputs/; \
        cp /root/bc9_outputs/*.json /var/cadets/bc9_online/bc9_outputs/ || echo 'No BC9 Outputs to restore' ; \
        cp /root/agm_outputs/*.json /var/cadets/agm/agm_outputs/ || echo 'No AGM outputs to restore' ; \
        cp /root/registrations.csv /var/cadets/agm/ || echo 'No AGM Registration Table to restore' ;"
    - name: Restore environment
      env:
        AGM_G_APPS_PASSWORD: ${{ secrets.NOREPLY_APP_PASSWORD }}
        SLACK_API_KEY: ${{ secrets.SLACK_API_KEY }}
        BC9_APP_PASSWORD: ${{ secrets.BC9_APP_PASSWORD }}
      run: |
        echo "BC9_APP_PASSWORD=${{ secrets.BC9_APP_PASSWORD }}" > .env
        echo "NOREPLY_APP_PASSWORD=${{ secrets.NOREPLY_APP_PASSWORD }}" >> .env
        echo "SLACK_API_KEY=${{ secrets.SLACK_API_KEY }}" >> .env
        echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
        chmod 0600 /tmp/ssh-key
        scp -o StrictHostKeyChecking=no -i /tmp/ssh-key .env root@server.talk-about-it.ca:/var/cadets/
        ssh -i /tmp/ssh-key -o StrictHostKeyChecking=no root@server.talk-about-it.ca " \
        systemctl is-active --quiet emperor.uwsgi.service && systemctl stop emperor.uwsgi.service; \
        systemctl start emperor.uwsgi.service"
